- name: Stop gitea container
  docker_container:
    name: gitea
    state: stopped
- name: Remove gitea container
  shell: |
    docker stop gitea
    docker rm gitea
- name: Recursively remove gitea directory
  ansible.builtin.file:
    path: /home/{{ cloud_user }}/gitea
    state: absent
