---
- name: Get UID
  getent:
    database: passwd
  when:
    - gitea_username is defined
    - gitea_password is defined
- name: Create a gitea directory
  ansible.builtin.file:
    path: /home/{{ cloud_user}}/gitea
    state: directory
    mode: '0755'
- name: Start gitea container
  shell: |
    docker run -d \
       --name gitea \
       --network kind \
       --user {{ getent_passwd[cloud_user].1 }}:{{ getent_passwd[cloud_user].2 }} \
       --restart always \
       -p 127.0.0.1:3000:3000/tcp \
       -p 127.0.0.1:2222:2222/tcp \
       -v /home/{{ cloud_user }}/gitea:/var/lib/gitea:rw \
       -e GITEA_APP_INI=/var/lib/gitea/custom/conf/app.ini \
       -e INSTALL_LOCK=true \
       gitea/gitea:1.17.3-rootless
  when:
    - gitea_username is defined
    - gitea_password is defined
- name: Wait for gitea to initialise
  ansible.builtin.wait_for:
    path: /home/{{ cloud_user }}/gitea/ssh
  when:
    - gitea_username is defined
    - gitea_password is defined
- name: Creating nephio user in gitea
  shell: |
    docker exec -it gitea \
      gitea admin user create \
        --username {{ gitea_username }} \
        --password {{ gitea_password }} \
        --must-change-password=false \
        --access-token \
        --email=nephio@nephio.org > /home/{{ cloud_user }}/gitea/nephio-create
  when:
    - gitea_username is defined
    - gitea_password is defined
- name: Creating nephio user in gitea
  shell: |
    grep 'Access token was successfully created... ' /home/{{ cloud_user }}/gitea/nephio-create | \
    sed 's/Access token was successfully created... //' | \
    tr -d '\r\n' > /home/{{ cloud_user }}/gitea/nephio-gitea-token
  when:
    - gitea_username is defined
    - gitea_password is defined
