## © 2022 Nokia
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: deploy nephio-system on mgmt cluster
  shell: kpt --kubeconfig ~/.kube/mgmt-config live init nephio-system
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already" not in result.stderr

- name: deploy nephio-system on mgmt cluster
  shell: kpt --kubeconfig ~/.kube/mgmt-config live apply nephio-system --reconcile-timeout=15m --output=table
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"

- name: deploy nephio-webui on mgmt cluster
  shell: kpt --kubeconfig ~/.kube/mgmt-config live init nephio-webui
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr

- name: deploy nephio-webui on mgmt cluster
  shell: kpt --kubeconfig ~/.kube/mgmt-config live apply nephio-webui
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"

- name: configure secret
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/mgmt-config apply -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-personal-access-token
      stringData:
        password: {{ github_token }}
        username: {{ github_username }}
      type: kubernetes.io/basic-auth
    EOF
  when:
    - github_username is defined

- name: Slurp gitea access token
  ansible.builtin.slurp:
    src: /home/{{ cloud_user }}/gitea/nephio-gitea-token
  register: gitea_token
  when:
    - gitea_username is defined

- name: configure gitea secret
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/mgmt-config apply -f -
      apiVersion: v1
      kind: Secret
      metadata:
        name: gitea-access-token
      stringData:
        password: {{ gitea_token['content'] | b64decode }}
        username: nephio
      type: kubernetes.io/basic-auth
    EOF
  when:
    - gitea_username is defined

- name: configure nephio ingress
  shell: |
    kubectl --kubeconfig ~/.kube/mgmt-config \
      apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

- name: wait for ingress controller
  shell: |
    kubectl wait --kubeconfig ~/.kube/mgmt-config \
      --namespace ingress-nginx \
      --for=condition=ready pod \
      --selector=app.kubernetes.io/component=controller \
      --timeout=180s

- name: configure nephio ingress
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/mgmt-config apply -f -
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: nephio-ingress
        namespace: nephio-webui
      spec:
        rules:
        - http:
            paths:
            - pathType: Prefix
              path: "/"
              backend:
                service:
                  name: nephio-webui
                  port:
                    number: 7007
    EOF
