---
- name: deploy nephio-configsync on {{ item.key }} cluster
  shell: kpt --kubeconfig ~/.kube/{{ item.key }}-config live init nephio-configsync
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already" not in result.stderr

- name: deploy nephio-configsync on {{ item.key }} cluster
  shell: kpt --kubeconfig ~/.kube/{{ item.key }}-config live apply nephio-configsync --reconcile-timeout=15m --output=table
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"

- name: configure secret on {{ item.key }}
  shell: |
    kubectl --kubeconfig ~/.kube/{{ item.key }}-config create secret generic github-personal-access-token \
    --namespace="config-management-system" \
    --from-literal=username={{github_username}} \
    --from-literal=token={{github_token}}
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr

- name: configure nephio-configsync
  shell: |
    cat <<EOF | kubectl --kubeconfig ~/.kube/{{ item.key }}-config apply -f -
      apiVersion: configsync.gke.io/v1beta1
      kind: RootSync
      metadata: # kpt-merge: config-management-system/nephio-mgmt-cluster-sync
        name: repo-{{ item.key }}-sync
        namespace: config-management-system
        annotations:
          config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/rootsyncs.configsync.gke.io
          internal.kpt.dev/upstream-identifier: 'configsync.gke.io|RootSync|config-management-system|nephio-mgmt-cluster-sync'
      spec:
        sourceFormat: unstructured
        git:
          repo: https://github.com/{{ github_organization}}/nephio-{{ item.key }}.git
          branch: main
          auth: token
          secretRef:
            name: github-personal-access-token
    EOF